### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by Marsel-marsel** [nccgroup/DetectWindowsCopyOnWriteForAPI#1]
Hello,

According to the README:

_Validate that NTDLL.dll is loaded and that EtwEventWrite is within the .text segement_
Ntdll exports _EtwEventWrite_, does it mean that this function is always within .text segment?

_Use QueryWorkingSetEx to check the page is shared OR not_
I think this step alone is enough to detect if dll was patched

**Comment by olliencc** [comment]
Dear @Marsel-marsel 

on #1 - I just check to ensure the address returned by GetProcAddress is indeed pointing to where we expect it to. This is to ensure that if any EAT modifications happen etc. we could detect.

on #2 - yes, but we need to know which and thus some of the extra work / validation.

Ollie
